### PR TITLE
Docs for pose2d usage

### PR DESCRIPTION
**Pull request by gerth2**
Closes https://github.com/PhotonVision/photonvision-docs/issues/112 with some generic statements. Could possibly also point to the simposeest example for context, but right now that's java only.

### CODE REVIEW

**Comment by mdurrani808** [comment]
Everything here looks good. 

Re: Could possibly also point to the simposeest example for context, but right now that's java only.
One of the original concerns was I've heard is that people want to see how to use the current Pose2D for a robot to generate a trajectory to the pose 2D of a target. 
Would you mind adding in a final step to the simposeest example page doing just that in this PR? I guess that would involve a photonvision PR as well for the code. Let me know what you think

**Comment by jasondaming** [comment]
Edited comment to include keyword to tie to the issue, here is the keyword list:
image

**Comment by gerth2** [comment]
> Everything here looks good.
> 
> Re: Could possibly also point to the simposeest example for context, but right now that's java only. One of the original concerns was I've heard is that people want to see how to use the current Pose2D for a robot to generate a trajectory to the pose 2D of a target. Would you mind adding in a final step to the simposeest example page doing just that in this PR? I guess that would involve a photonvision PR as well for the code. Let me know what you think


yes...ish. So here's my $0.02 on the topic. We should have a canonical, "all bells and whistles" example. Sim Pose Est is close to that, but as you pointed out lacks trajectory generation and autonomous.

However, I worry that gets a bit outside the scope of vision processing itself. The key is to present the potential, without being so prescriptive as to invite folks to reference the photonvision example as "necessarily correct for their situation". It move photonvision's docs out of "explaining how to use photonvision", and into a "educate users on how to do vision processing well" space. This isn't bad, just a change to be cognizant of. 

W're already down that path by having _any_ examples. I think the best path forward is to add a new example that builds on sim pose estimation and shows how to do pathplanning/ramsete, all with wpi stuff.

In terms of mechanics.... I'd say two new issues, one for photon and one for docs here?

**Comment by mdurrani808** [comment]
> yes...ish. So here's my $0.02 on the topic. We should have a canonical, "all bells and whistles" example. Sim Pose Est is close to that, but as you pointed out lacks trajectory generation and autonomous.
> 
> However, I worry that gets a bit outside the scope of vision processing itself. The key is to present the potential, without being so prescriptive as to invite folks to reference the photonvision example as "necessarily correct for their situation". It move photonvision's docs out of "explaining how to use photonvision", and into a "educate users on how to do vision processing well" space. This isn't bad, just a change to be cognizant of.
> 
> W're already down that path by having _any_ examples. I think the best path forward is to add a new example that builds on sim pose estimation and shows how to do pathplanning/ramsete, all with wpi stuff.
> 
> In terms of mechanics.... I'd say two new issues, one for photon and one for docs here?

This all makes sense, I agree. I think a good middle ground (for now, while other examples potentially get written) would be to drop a line at the end of the example that says, hey, now that you have all of this set up you can do things like generate trajectories from anywhere on the field, (something), and (something else) without explicitly writing out those examples there. 

Thoughts?

**Comment by gerth2** [comment]
> 

I think that works by me.

To clarify, after re-reading all the posts, I think that there are at least two possible things one could do with a Pose2D that photonlib returns:

1) Incorporate vision into a pose estimate in a field-global reference frame, and path plan based on known position of the target.
2) Path-plan in a reference frame centered on the target itself

Adding statements on this docs page to describe these both should be just fine.

Does this cover the expected use cases?

**Comment by calcmogul** [comment]
Yea, those two should cover it.

**Comment by gerth2** [comment]
#132 supersedes this.

**Pull request closed without merging**
