### PR TITLE
Remove gloworm links

### PR DESCRIPTION
**Pull request by mdurrani808**
gloworm.vision is no longer hosted, we need to remove the links

May be worth it to look into making sure we are able to still generate gloworm images should one need them (if franklin will no longer provide them).

### CODE REVIEW

**Comment by mcm001** [comment]
We can also use an archive.org link?

**Comment by mcm001** [comment]
https://web.archive.org/web/20220525051734/https://gloworm.vision/

**Review by mcm001 — APPROVED** [review]

**Comment by mdurrani808** [comment]
prepare for the most ludicrous example of git wizardry you've ever seen

**Comment by mdurrani808** [comment]
nobody does git like i do

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
