### PR TITLE
Add some notes about restricting the CPU cores used by PV

### PR DESCRIPTION
**Pull request by prensing**
I added a few "notes" in the install docs to point people to the ability to restrict which CPU cores are used. This is relevant on ARM big.LITTLE architectures, including Orange Pi 5.

### CODE REVIEW

**Comment by mcm001** [comment]
FYI, I have a PR open to create a orange pi image with this flag set by default in the service file. Lgtm tho

**Review by mcm001 — APPROVED** [review]

**Comment by mcm001** [comment]
Needs to be rebased

**Comment by prensing** [comment]
Done. Hopefully correctly (not a git wizard!).

**Comment by mcm001** [comment]
Looks completely FUBAR

**Comment by prensing** [comment]
OK, I did not notice a link had changed. Should have tested my build ;-(. Done, and CI passes now.

**Comment by mcm001** [comment]
I still see 103 files changed????

**Comment by prensing** [comment]
OK, I am mystified. I only touched 2 files. It looks like somehow it dragged into a bunch of other commits from mdurranni808 2 days ago. No idea how that is possible. 
Maybe I will just kill this and then resubmit, but I can't right now (need to run).

**Comment by prensing** [comment]
Actually, snuck it in. See PR306. I did not bother with the note in the OPi page, because I don't know about the OPi 4.

**Pull request closed without merging**
