### PR TITLE
Fixed a few small spelling + grammar mistakes

### PR DESCRIPTION
**Pull request by gautvm**
Found while reading the docs

### CODE REVIEW

**Comment by gautvm** [comment]
Found a lot more ^

**Comment by mcm001** [comment]
we really need a spell checker

**Review by mcm001 — APPROVED** [review]

**Comment by Cypheriel** [comment]
I would suggest borrowing some fixes from #352 (which is now closed)

**Comment by mdurrani808** [comment]
You ever have those words you've been spelling wrong your whole life? Recommend is one of those words, maybe its just me. Thanks!

**Pull request merged**
