### PR TITLE
Expand sidebar

### LINKED ISSUE #137: Refactor sidebar
Currently, too many things are hidden under folders. This should be expanded.

### PR DESCRIPTION
**Pull request by mdurrani808**
Closes #137

### CODE REVIEW

**Review by gerth2 — COMMENTED** [review]
I haven't explicitly tried to build this one yet. I'd say merge it, and we can review titles after the fact.

**Comment by mdurrani808** [comment]
image
@gerth2 This is what the titles look like atm.

**Review by mcm001 — APPROVED** [review]

**Comment by gerth2** [comment]
Sweet I think it's an awesome start. I've got a few ideas for titles/order I'll start a new PR for once this is merged.

**Comment by mdurrani808** [comment]
> Sweet I think it's an awesome change. I've got a few ideas for titles/order I'll start a new PR for once this is merged.

@gerth2 If you've got the time, it would probably be best to make the PR for that based off of my branch once I fix the merge conflicts tonight so we can get all the sidebar stuff merged on the 4th to align with the WPILib / frc-docs / main image release. If you don't have time, feel free to drop the titles here and I'll add them in.

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
